'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'

type Reservation={id:string;created_at:string;status:string;payment_status:string|null;payment_total:number|null;total:number;payment_method:string|null}
type Vehicle={id:string;status:string}
const brl=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const months=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez']

export default function AdminPage(){
 const [allowed,setAllowed]=useState<boolean|null>(null),[name,setName]=useState('Administrador'),[reservations,setReservations]=useState<Reservation[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[clients,setClients]=useState(0)
 useEffect(()=>{(async()=>{if(!supabase){setAllowed(false);return}const {data:{user}}=await supabase.auth.getUser();if(!user){setAllowed(false);return}const {data:p}=await supabase.from('profiles').select('role,full_name').eq('id',user.id).single();const ok=p?.role==='admin'||p?.role==='manager';setAllowed(ok);if(p?.full_name)setName(p.full_name);if(!ok)return;const [{data:r},{data:v},{count:c}]=await Promise.all([supabase.from('reservations').select('id,created_at,status,payment_status,payment_total,total,payment_method').order('created_at'),supabase.from('vehicles').select('id,status'),supabase.from('profiles').select('id',{count:'exact',head:true}).eq('role','customer')]);setReservations((r||[]) as Reservation[]);setVehicles((v||[]) as Vehicle[]);setClients(c||0)})()},[])
 async function logout(){if(supabase)await supabase.auth.signOut();window.location.href='/login'}
 const stats=useMemo(()=>{const paid=reservations.filter(r=>r.payment_status==='paid');const revenue=paid.reduce((s,r)=>s+Number(r.payment_total??r.total??0),0);return{total:reservations.length,pending:reservations.filter(r=>r.status==='pending').length,confirmed:reservations.filter(r=>r.status==='confirmed').length,active:reservations.filter(r=>r.status==='active').length,cancelled:reservations.filter(r=>r.status==='cancelled').length,paid:paid.length,revenue,available:vehicles.filter(v=>v.status==='available').length,reserved:vehicles.filter(v=>v.status==='reserved').length,maintenance:vehicles.filter(v=>v.status==='maintenance').length}},[reservations,vehicles])
 const monthly=useMemo(()=>{const y=new Date().getFullYear();return months.map((label,m)=>({label,value:reservations.filter(r=>{const d=new Date(r.created_at);return d.getFullYear()===y&&d.getMonth()===m}).length,revenue:reservations.filter(r=>{const d=new Date(r.created_at);return d.getFullYear()===y&&d.getMonth()===m&&r.payment_status==='paid'}).reduce((s,r)=>s+Number(r.payment_total??r.total??0),0)}))},[reservations])
 const maxMonth=Math.max(1,...monthly.map(m=>m.value))
 if(allowed===null)return <main className="container"><div className="card">Verificando acesso...</div></main>
 if(!allowed)return <main className="container"><section className="hero"><h1>Painel administrativo</h1><p>Área restrita do AGENDA-GO.</p></section><div className="card"><p>Você precisa entrar com uma conta de administrador ou gerente.</p><a className="btn" href="/login">Ir para o login</a></div></main>
 return <main className="container"><section className="hero"><h1>Dashboard administrativo</h1><p>Bem-vindo, {name}. Acompanhe reservas, faturamento, clientes e frota do AGENDA-GO.</p></section>
 <section className="kpiGrid"><div className="kpiCard"><span>Reservas</span><strong>{stats.total}</strong><small>{stats.pending} pendente(s)</small></div><div className="kpiCard"><span>Faturamento pago</span><strong>{brl(stats.revenue)}</strong><small>{stats.paid} pagamento(s)</small></div><div className="kpiCard"><span>Clientes</span><strong>{clients}</strong><small>cadastros</small></div><div className="kpiCard"><span>Veículos livres</span><strong>{stats.available}</strong><small>{stats.reserved} reservado(s)</small></div></section>
 <section className="dashboardTwo"><div className="card"><h2>Reservas por mês</h2><div className="barChart">{monthly.map(m=><div className="barCol" key={m.label}><div className="barValue">{m.value}</div><div className="bar" style={{height:`${Math.max(5,(m.value/maxMonth)*180)}px`}}></div><span>{m.label}</span></div>)}</div></div><div className="card"><h2>Status da operação</h2><div className="statusList"><div><span>Pendentes</span><strong>{stats.pending}</strong></div><div><span>Confirmadas</span><strong>{stats.confirmed}</strong></div><div><span>Em andamento</span><strong>{stats.active}</strong></div><div><span>Canceladas</span><strong>{stats.cancelled}</strong></div><div><span>Em manutenção</span><strong>{stats.maintenance}</strong></div></div></div></section>
 <section className="section grid"><a className="card" href="/admin/nova-reserva" style={{textDecoration:'none',color:'inherit'}}><h3>Nova reserva</h3><div className="value">Reservar</div><p>Crie uma locação para um cliente.</p></a><a className="card" href="/admin/reservas" style={{textDecoration:'none',color:'inherit'}}><h3>Reservas</h3><div className="value">Gerenciar</div><p>Confirme, inicie, finalize ou cancele.</p></a><a className="card" href="/admin/veiculos" style={{textDecoration:'none',color:'inherit'}}><h3>Veículos</h3><div className="value">Frota</div><p>Cadastre e acompanhe os veículos.</p></a><a className="card" href="/admin/clientes" style={{textDecoration:'none',color:'inherit'}}><h3>Clientes</h3><div className="value">Cadastros</div><p>CPF, CNH, telefone e endereço.</p></a><a className="card" href="/admin/pagamentos" style={{textDecoration:'none',color:'inherit'}}><h3>Pagamentos</h3><div className="value">Configurar</div><p>PIX, cartão e taxas.</p></a><a className="card" href="/admin/relatorios" style={{textDecoration:'none',color:'inherit'}}><h3>Relatórios</h3><div className="value">Completo</div><p>Período, faturamento, reservas e pagamentos.</p></a></section>
 <section className="section card"><div className="actions"><a className="btn" href="/admin/nova-reserva">+ Nova reserva</a><a className="btn secondary" href="/admin/relatorios">Relatórios</a><a className="btn secondary" href="/admin/reservas">Reservas</a><a className="btn secondary" href="/admin/veiculos">Veículos</a><button className="btn" onClick={logout}>Sair do administrador</button></div></section></main>
}