'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'

type Company={id:string;name:string;slug:string|null;status:string|null;created_at:string}
type Reservation={id:string;status:string;total:number|null;payment_total:number|null;payment_status:string|null;payment_method:string|null;platform_fee:number|null;platform_net:number|null;company_id:string|null;created_at:string}
type Payment={id:string;amount:number;status:string;method:string;company_id:string|null;created_at:string}

const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const monthLabel=(d:Date)=>d.toLocaleDateString('pt-BR',{month:'short'}).replace('.','')

export default function SuperAdmin(){
 const [ok,setOk]=useState<boolean|null>(null),[companies,setCompanies]=useState<Company[]>([]),[reservations,setReservations]=useState<Reservation[]>([]),[payments,setPayments]=useState<Payment[]>([]),[clients,setClients]=useState(0),[vehicles,setVehicles]=useState(0)
 useEffect(()=>{(async()=>{if(!supabase){setOk(false);return}const {data:{user}}=await supabase.auth.getUser();if(!user){setOk(false);return}const {data:p}=await supabase.from('profiles').select('is_super_admin').eq('id',user.id).single();const allowed=!!p?.is_super_admin;setOk(allowed);if(!allowed)return;const [c,r,pa,cl,v]=await Promise.all([supabase.from('companies').select('id,name,slug,status,created_at').order('created_at',{ascending:false}),supabase.from('reservations').select('id,status,total,payment_total,payment_status,payment_method,platform_fee,platform_net,company_id,created_at').order('created_at',{ascending:false}),supabase.from('payments').select('id,amount,status,method,company_id,created_at').order('created_at',{ascending:false}),supabase.from('profiles').select('id',{count:'exact',head:true}).eq('role','customer'),supabase.from('vehicles').select('id',{count:'exact',head:true})]);setCompanies((c.data||[]) as Company[]);setReservations((r.data||[]) as Reservation[]);setPayments((pa.data||[]) as Payment[]);setClients(cl.count||0);setVehicles(v.count||0)})()},[])
 const activeCompanies=companies.filter(c=>c.status!=='blocked'&&c.status!=='inactive').length
 const paidReservations=reservations.filter(r=>r.payment_status==='paid')
 const gross=paidReservations.reduce((s,r)=>s+Number(r.payment_total??r.total??0),0)
 const platformRevenue=paidReservations.reduce((s,r)=>s+Number(r.platform_net??r.platform_fee??0),0)
 const pendingValue=reservations.filter(r=>r.payment_status!=='paid'&&r.status!=='cancelled').reduce((s,r)=>s+Number(r.payment_total??r.total??0),0)
 const monthly=useMemo(()=>{const rows=[] as {label:string;reservations:number;revenue:number}[];for(let i=5;i>=0;i--){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-i);const y=d.getFullYear(),m=d.getMonth();const rs=reservations.filter(r=>{const x=new Date(r.created_at);return x.getFullYear()===y&&x.getMonth()===m});rows.push({label:monthLabel(d),reservations:rs.length,revenue:rs.filter(r=>r.payment_status==='paid').reduce((s,r)=>s+Number(r.platform_net??r.platform_fee??0),0)})}return rows},[reservations])
 const maxReservations=Math.max(1,...monthly.map(x=>x.reservations)),maxRevenue=Math.max(1,...monthly.map(x=>x.revenue))
 if(ok===null)return <main className="container"><div className="card">Carregando Super Admin...</div></main>
 if(!ok)return <main className="container"><div className="card"><h1>Acesso restrito</h1><p>Este painel é exclusivo do Super Admin AGENDA-GO.</p><a className="btn" href="/login">Entrar</a></div></main>
 return <main className="container"><section className="hero"><h1>Super Admin AGENDA-GO</h1><p>Visão consolidada de todas as locadoras, reservas, pagamentos e receita da plataforma.</p></section>
 <section className="superStats"><div className="card metricCard"><span>Locadoras</span><strong>{companies.length}</strong><small>{activeCompanies} ativas</small></div><div className="card metricCard"><span>Reservas</span><strong>{reservations.length}</strong><small>{reservations.filter(r=>r.status==='pending').length} pendentes</small></div><div className="card metricCard"><span>Volume processado</span><strong>{money(gross)}</strong><small>reservas pagas</small></div><div className="card metricCard"><span>Receita AGENDA-GO</span><strong>{money(platformRevenue)}</strong><small>comissões registradas</small></div><div className="card metricCard"><span>A receber</span><strong>{money(pendingValue)}</strong><small>pagamentos pendentes</small></div><div className="card metricCard"><span>Base da plataforma</span><strong>{clients}</strong><small>{vehicles} veículos cadastrados</small></div></section>
 <section className="superCharts section"><div className="card"><h2>Reservas — últimos 6 meses</h2><div className="barChart">{monthly.map(x=><div className="barCol" key={x.label}><div className="barValue">{x.reservations}</div><div className="barTrack"><div className="barFill" style={{height:`${Math.max(5,x.reservations/maxReservations*100)}%`}}/></div><span>{x.label}</span></div>)}</div></div><div className="card"><h2>Receita AGENDA-GO — 6 meses</h2><div className="barChart">{monthly.map(x=><div className="barCol" key={x.label}><div className="barValue small">{money(x.revenue)}</div><div className="barTrack"><div className="barFill dark" style={{height:`${Math.max(5,x.revenue/maxRevenue*100)}%`}}/></div><span>{x.label}</span></div>)}</div></div></section>
 <section className="section card"><h2>Gestão central</h2><div className="actions"><a className="btn" href="/super-admin/locadoras">Locadoras</a><a className="btn secondary" href="/super-admin/tarifas">Tarifas e comissões</a><a className="btn secondary" href="/super-admin/relatorios">Relatórios completos</a></div></section>
 <section className="section card"><h2>Locadoras recentes</h2>{companies.length===0?<p>Nenhuma locadora cadastrada.</p>:companies.slice(0,8).map(c=><div className="rowItem" key={c.id}><strong>{c.name}</strong><span>Status: {c.status==='blocked'?'Bloqueada':'Ativa'} • Link: /l/{c.slug||c.id}</span><div className="actions"><a className="btn secondary" href="/super-admin/locadoras">Gerenciar</a>{c.slug&&<a className="btn" href={'/l/'+c.slug} target="_blank">Abrir locadora</a>}</div></div>)}</section></main>
}