'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../../lib/supabase'

type Item={id:string;created_at:string;pickup_at:string;return_at:string;status:string;payment_status:string|null;payment_method:string|null;payment_total:number|null;total:number;customer_phone:string|null;vehicles:{name:string}|null;profiles:{full_name:string|null}|null}
const brl=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const statusPt:Record<string,string>={pending:'Pendente',confirmed:'Confirmada',active:'Em andamento',completed:'Concluída',cancelled:'Cancelada'}
export default function Relatorios(){
 const [allowed,setAllowed]=useState<boolean|null>(null),[items,setItems]=useState<Item[]>([]),[from,setFrom]=useState(''),[to,setTo]=useState('')
 useEffect(()=>{(async()=>{if(!supabase){setAllowed(false);return}const {data:{user}}=await supabase.auth.getUser();if(!user){setAllowed(false);return}const {data:p}=await supabase.from('profiles').select('role').eq('id',user.id).single();const ok=p?.role==='admin'||p?.role==='manager';setAllowed(ok);if(!ok)return;const {data}=await supabase.from('reservations').select('id,created_at,pickup_at,return_at,status,payment_status,payment_method,payment_total,total,customer_phone,vehicles(name),profiles!reservations_customer_id_fkey(full_name)').order('created_at',{ascending:false});setItems((data||[]) as unknown as Item[])})()},[])
 const filtered=useMemo(()=>items.filter(i=>{const d=new Date(i.created_at).getTime();const a=from?new Date(from+'T00:00:00').getTime():-Infinity;const b=to?new Date(to+'T23:59:59').getTime():Infinity;return d>=a&&d<=b}),[items,from,to])
 const totals=useMemo(()=>{const paid=filtered.filter(i=>i.payment_status==='paid');return{reservas:filtered.length,pagas:paid.length,receita:paid.reduce((s,i)=>s+Number(i.payment_total??i.total??0),0),pendente:filtered.filter(i=>i.payment_status!=='paid'&&i.status!=='cancelled').reduce((s,i)=>s+Number(i.payment_total??i.total??0),0),pix:filtered.filter(i=>i.payment_method==='pix').length,card:filtered.filter(i=>i.payment_method==='card').length,canceladas:filtered.filter(i=>i.status==='cancelled').length}},[filtered])
 function printReport(){window.print()}
 if(allowed===null)return <main className="container"><div className="card">Carregando relatório...</div></main>
 if(!allowed)return <main className="container"><div className="card">Acesso restrito.</div></main>
 return <main className="container"><section className="hero"><h1>Relatório completo</h1><p>Analise reservas, pagamentos e faturamento por período.</p></section><section className="card reportFilters"><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="btn secondary" onClick={()=>{setFrom('');setTo('')}}>Limpar</button><button className="btn" onClick={printReport}>Imprimir / Salvar PDF</button></section><section className="kpiGrid section"><div className="kpiCard"><span>Reservas</span><strong>{totals.reservas}</strong></div><div className="kpiCard"><span>Receita paga</span><strong>{brl(totals.receita)}</strong></div><div className="kpiCard"><span>A receber</span><strong>{brl(totals.pendente)}</strong></div><div className="kpiCard"><span>Canceladas</span><strong>{totals.canceladas}</strong></div></section><section className="dashboardTwo section"><div className="card"><h2>Pagamentos</h2><div className="statusList"><div><span>Pagos</span><strong>{totals.pagas}</strong></div><div><span>PIX</span><strong>{totals.pix}</strong></div><div><span>Cartão</span><strong>{totals.card}</strong></div></div></div><div className="card"><h2>Resumo financeiro</h2><div className="statusList"><div><span>Recebido</span><strong>{brl(totals.receita)}</strong></div><div><span>Pendente</span><strong>{brl(totals.pendente)}</strong></div><div><span>Ticket médio pago</span><strong>{brl(totals.pagas?totals.receita/totals.pagas:0)}</strong></div></div></div></section><section className="card section reportTableWrap"><h2>Detalhamento das reservas</h2><table className="reportTable"><thead><tr><th>Data</th><th>Cliente</th><th>Veículo</th><th>Período</th><th>Pagamento</th><th>Valor</th><th>Status</th></tr></thead><tbody>{filtered.map(i=><tr key={i.id}><td>{new Date(i.created_at).toLocaleDateString('pt-BR')}</td><td>{i.profiles?.full_name||'Cliente'}<br/><small>{i.customer_phone||''}</small></td><td>{i.vehicles?.name||'—'}</td><td>{new Date(i.pickup_at).toLocaleDateString('pt-BR')} a {new Date(i.return_at).toLocaleDateString('pt-BR')}</td><td>{i.payment_method==='card'?'Cartão':'PIX'}<br/><small>{i.payment_status==='paid'?'Pago':'Pendente'}</small></td><td>{brl(Number(i.payment_total??i.total??0))}</td><td>{statusPt[i.status]||i.status}</td></tr>)}</tbody></table>{filtered.length===0&&<p>Nenhuma reserva no período selecionado.</p>}</section></main>
}