import {NextResponse} from 'next/server'
import https from 'node:https'
import {createHash} from 'node:crypto'
export const runtime='nodejs'
export const dynamic='force-dynamic'

const host='pix.api.efipay.com.br'
function certificate(){const raw=(process.env.EFI_CERTIFICATE_BASE64||'').replace(/\s/g,'');if(!raw)throw new Error('MISSING_CERT');return Buffer.from(raw,'base64')}
function certificateSha256(){const raw=(process.env.EFI_CERTIFICATE_BASE64||'').replace(/\s/g,'');return raw?createHash('sha256').update(Buffer.from(raw,'base64')).digest('hex'):null}
function oauth(){return new Promise<any>((resolve,reject)=>{const clientId=process.env.EFI_CLIENT_ID||'',clientSecret=process.env.EFI_CLIENT_SECRET||'';if(!clientId||!clientSecret)return reject(new Error('MISSING_CREDENTIALS'));const payload=JSON.stringify({grant_type:'client_credentials'});const req=https.request({hostname:host,port:443,path:'/oauth/token',method:'POST',pfx:certificate(),passphrase:process.env.EFI_CERTIFICATE_PASSWORD||'',rejectUnauthorized:true,headers:{Authorization:`Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString('base64')}`,'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload),Accept:'application/json','User-Agent':'CLICK-FOOD-EfiScopeCheck/1.0'}},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>{let data:any={};try{data=raw?JSON.parse(raw):{}}catch{}const status=res.statusCode||500;if(status<200||status>=300||!data.access_token)return reject(new Error(`EFI_HTTP_${status}`));resolve({status,tokenPresent:true,scope:String(data.scope||'').split(/\s+/).filter(Boolean),expiresIn:Number(data.expires_in||0)})})});req.on('error',reject);req.setTimeout(20000,()=>req.destroy(new Error('EFI_TIMEOUT')));req.write(payload);req.end()})}
export async function GET(){const configured={clientId:Boolean(process.env.EFI_CLIENT_ID),clientSecret:Boolean(process.env.EFI_CLIENT_SECRET),certificate:Boolean(process.env.EFI_CERTIFICATE_BASE64),pixKey:Boolean(process.env.EFI_PIX_KEY),environment:process.env.EFI_SANDBOX==='true'?'sandbox':'production'};try{const auth=await oauth();return NextResponse.json({ok:true,configured,providerStatus:auth.status,tokenPresent:auth.tokenPresent,scope:auth.scope,expiresIn:auth.expiresIn,certificateSha256:certificateSha256()},{headers:{'Cache-Control':'no-store'}})}catch(error:any){return NextResponse.json({ok:false,configured,error:String(error?.message||'EFI_AUTH_FAILED'),certificateSha256:certificateSha256()},{status:200,headers:{'Cache-Control':'no-store'}})}}
